version: 0.2
env:
  secrets-manager:
    NVD_API_KEY: "arn:aws:secretsmanager:us-east-1:585008079716:secret:NVD_API_KEY-8aSdnM"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Installing OWASP Dependency-Check...
      - curl -L https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip -o dependency-check.zip
      - unzip dependency-check.zip
      - chmod +x dependency-check/bin/dependency-check.sh
  pre_build:
    commands:
      - echo Running OWASP Dependency-Check scan...
      - echo "NVD API KEY $NVD_API_KEY"
      - ls
      - dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --nvdApiKey $NVD_API_KEY --out build --nvdApiEndpoint https://services.nvd.nist.gov/rest/json/cves/2.0/?resultsPerPage=1000&startIndex=0
      - ls -l build
  build:
    commands:
      - echo Building Node.js application...
      - npm run build
  post_build:
    commands:
      - echo Build completed.
      - echo Dependency-Check report generated at dependency-check-report/dependency-check-report.html
      - aws s3 cp Skycast/build/dependency-check-report.html s3://first-sonarqube/dependency-check-report.html
      - echo "Report uploaded to S3"
