version: 0.2
env:
  variables:
    NVD_API_KEY: "19fe0687-a48d-4008-bec0-f77f385cc2b3"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Installing OWASP Dependency-Check...
      - curl -L https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip -o dependency-check.zip
      - unzip dependency-check.zip
      - chmod +x dependency-check/bin/dependency-check.sh
  pre_build:
    commands:
      - echo Running OWASP Dependency-Check scan...
      - echo NVD API KEY $NVD_API_KEY
      - ls
      - dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --nvdApiKey $NVD_API_KEY --out build --nvdApiEndpoint https://services.nvd.nist.gov/rest/json/cves/2.0/?resultsPerPage=1000
  build:
    commands:
      - echo Building Node.js application...
      - npm run build
