version: 0.2
env:
  secrets-manager:
    NVD_API_KEY: "arn:aws:secretsmanager:us-east-1:585008079716:secret:NVD_API_KEY-8aSdnM"

phases:
  pre_build:
    commands:
      - echo Running OWASP Dependency-Check scan...
      - ls
      - dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --nvdApiKey $NVD_API_KEY  --out build --noupdate
      - cd build
      - ls
  post_build:
    commands:
      - echo Build completed.
      - echo Dependency-Check report generated at dependency-check-report/dependency-check-report.html
